# fly.toml app configuration file generated for speed-chat-api on 2025-01-27T00:00:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "speed-chat-api"
primary_region = "bog"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
